version: 2
jobs:
  test-all:
    docker:
      - image: sudachen/go-ml-ci

    parallelism: 1

    environment:
      MXNET_ENFORCE_DETERMINISM: 1
      OMP_NUM_THREADS: 4
      MXNET_OMP_MAX_THREADS: 4
      CC_TEST_REPORTER_ID: 447285c5d960b13fa6d1d3d8abd2e35b533fce8c8d7993ddd751c52736ca4f58

    steps:
      - checkout

      - restore_cache:
          # https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run: git clone https://github.com/sudachen/go-iokit

      - run: make build

      - run: make run-tests

      - run: /usr/local/bin/cc-test-reporter after-build -t gocov

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-all